/**
 * Generate CSS Variables from Design Tokens
 * 
 * This script reads the TypeScript design tokens and generates CSS custom properties
 * that can be used in Tailwind's theme configuration and directly in components.
 * 
 * Run with: npm run tokens:generate
 */

/* eslint-disable @typescript-eslint/no-require-imports */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable no-console */

const fs = require('fs');
const path = require('path');
const tokens = require('../src/design-system/tokens');

const { colors, spacing, radii, shadows, typography, zIndex } = tokens;

/**
 * Flattens a nested object into CSS variable format
 * Example: { primary: { DEFAULT: '#123' } } => --color-primary: #123
 */
function flattenObject(
  obj: any,
  prefix: string = '',
  separator: string = '-'
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}${separator}${key}` : key;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Handle special cases like fontSize which has { size, lineHeight }
      if ('size' in value && 'lineHeight' in value) {
        result[newKey] = (value as any).size;
        result[`${newKey}-line-height`] = (value as any).lineHeight;
      } else if (key === 'DEFAULT') {
        // Handle DEFAULT keys - merge up to parent level
        result[prefix] = String(value);
      } else {
        // Recursively flatten nested objects
        Object.assign(result, flattenObject(value, newKey, separator));
      }
    } else {
      result[newKey] = String(value);
    }
  }

  return result;
}

/**
 * Converts a flat object to CSS custom properties
 */
function generateCSSVariables(tokens: Record<string, string>, prefix: string): string {
  const lines = Object.entries(tokens).map(([key, value]) => {
    // Remove 'DEFAULT' from key names as they're already flattened
    const cleanKey = key.replace(/-DEFAULT$/, '');
    return `  --${prefix}-${cleanKey}: ${value};`;
  });

  return lines.join('\n');
}

/**
 * Main function to generate the CSS file
 */
function generateTokensCSS() {
  const cssContent = `/**
 * Design System Tokens - CSS Variables
 * 
 * Auto-generated from src/design-system/tokens.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To update these tokens:
 * 1. Edit src/design-system/tokens.ts
 * 2. Run: npm run tokens:generate
 */

:root {
  /* ========================================================================
     COLORS
     ======================================================================== */
${generateCSSVariables(flattenObject(colors), 'color')}

  /* ========================================================================
     SPACING
     ======================================================================== */
${generateCSSVariables(flattenObject(spacing), 'spacing')}

  /* ========================================================================
     RADII (Border Radius)
     ======================================================================== */
${generateCSSVariables(flattenObject(radii), 'radius')}

  /* ========================================================================
     SHADOWS
     ======================================================================== */
${generateCSSVariables(flattenObject(shadows), 'shadow')}

  /* ========================================================================
     TYPOGRAPHY
     ======================================================================== */
${generateCSSVariables(flattenObject(typography), 'font')}

  /* ========================================================================
     Z-INDEX
     ======================================================================== */
${generateCSSVariables(flattenObject(zIndex), 'z')}
}
`;

  // Write the CSS file
  const outputPath = path.join(__dirname, '../src/design-system/tokens.css');
  
  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, cssContent, 'utf-8');
  
  console.log('✅ Design tokens CSS generated successfully!');
  console.log(`📝 Output: ${outputPath}`);
  console.log('\n💡 Import this file in your globals.css:');
  console.log('   @import "./design-system/tokens.css";');
}

// Run the generator
try {
  generateTokensCSS();
} catch (error) {
  console.error('❌ Error generating CSS tokens:', error);
  process.exit(1);
}

